name: FDGT
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - cudatoolkit=11.1
  - numpy
  - pandas
  - python=3.9
  - pytorch=1.9.0
  - scipy>=1.10.0
  - numpy>=1.23.5
  - pandas>=1.5.2
  - pyyaml
  - statsmodels
  - tables
  - futurese    
  - configparser    
  - sklearn
